#!/bin/bash

cd ../../../../
echo $(pwd)
PWD_DIR=$(pwd)

cd scripts
./halclean
cd ..
cd bin
	
# stop hal.
./halcmd stop

# Load rt component:
#
# When using > 3 DoFs increase period2, also change timer in cpp_interface at_time, ~line 52
./halcmd loadrt threads name1=base-thread fp1=0 period1=25000 name2=servo-thread period2=1000000

# Standard up to 6 DoFs synchronized by time.
./halcmd loadrt synchrodofs nr=3

./halcmd addf synchrodofs.run servo-thread

# start hal.
./halcmd start

./halcmd setp synchrodofs.enable.0           1        # bool 0-1
./halcmd setp synchrodofs.maxvel.0           100      # max velocity
./halcmd setp synchrodofs.maxacc.0           10       # max acceleration
./halcmd setp synchrodofs.maxjerk.0          5        # max jerk
./halcmd setp synchrodofs.tarpos.0           500      # targetposition

./halcmd setp synchrodofs.enable.1           1
./halcmd setp synchrodofs.maxvel.1           200
./halcmd setp synchrodofs.maxacc.1           10
./halcmd setp synchrodofs.maxjerk.1          5
./halcmd setp synchrodofs.tarpos.1           600

./halcmd setp synchrodofs.enable.2           1
./halcmd setp synchrodofs.maxvel.2           300
./halcmd setp synchrodofs.maxacc.2           10
./halcmd setp synchrodofs.maxjerk.2          5
./halcmd setp synchrodofs.tarpos.2           700

./halcmd show
