#!/bin/bash
cd ../../../../

cd scripts
. ./rip-environment
./halclean
cd  ..
cd bin
./halcmd stop
./halcmd loadrt threads name1=base-thread fp1=0 period1=15000 name2=servo-thread period2=1000000
./halcmd loadrt interface nr=1
./halcmd addf interface.run servo-thread
./halcmd addf interface.pulse base-thread
./halcmd start
#./halcmd show


