#!/bin/bash

cd ../../../../
echo $(pwd)
# At hal-core source place.
PWD_DIR=$(pwd) 

cd scripts
./halclean
cd ..
cd bin

./halcmd stop

./halcmd loadrt threads name1=base-thread fp1=0 period1=25000 name2=servo-thread period2=1000000
./halcmd loadrt hal_kinematic

./halcmd addf hal_kinematic servo-thread

./halcmd \-f $PWD_DIR/src/hal/components/kinematic/machinemodel.hal

./halcmd start

./halcmd show




