#!/usr/bin/bash
cd ../../../../

echo $(pwd)

cd scripts 
./halclean
cd ..

cd bin

./halcmd stop
./halcmd loadrt threads name1=base-thread fp1=0 period1=25000 name2=servo-thread period2=1000000
./halcmd loadrt motion
./halcmd addf motion_update servo-thread
#./halcmd setp motion.Xfwd 1
./halcmd start
./halcmd show
