#!/bin/bash
cd ../../../../
echo $(pwd)
cd scripts
./halclean
cd  ..
cd bin
./halcmd stop
./halcmd loadrt threads name1=base-thread fp1=0 period1=15000 name2=servo-thread period2=1000000
./halcmd loadrt dofs nr=1
./halcmd addf dofs.run servo-thread
./halcmd addf dofs.pulse base-thread
./halcmd start
./halcmd show


